using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace LightMapper.SourceGenerators;

internal sealed class DependencyInjectionEmitter
{
    private static readonly SymbolDisplayFormat FullyQualified =
        SymbolDisplayFormat.FullyQualifiedFormat;

    private readonly ImmutableArray<MappingDeclaration> _pairs;

    public DependencyInjectionEmitter(ImmutableArray<MappingDeclaration> pairs)
    {
        _pairs = pairs;
    }

    public void Emit(SourceProductionContext context)
    {
        var sb = new StringBuilder(4096);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("namespace LightMapper.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Registers all generated <see cref=\"global::LightMapper.ILightMapper{TSource, TDestination}\"/> singletons without reflection.</summary>");
        sb.AppendLine("    public static class LightMapperServiceCollectionExtensions");
        sb.AppendLine("    {");
        sb.AppendLine("        public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddLightMapperMappers(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("        {");

        foreach (var pair in _pairs)
        {
            var srcFq = pair.Source.ToDisplayString(FullyQualified);
            var dstFq = pair.Destination.ToDisplayString(FullyQualified);
            var mapperType = MappingCodeEmitter.MapperTypeName(pair.Source, pair.Destination);
            sb.AppendLine($"            global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<global::LightMapper.ILightMapper<{srcFq}, {dstFq}>>(services, {mapperType}.Instance);");
        }

        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        context.AddSource("LightMapper.Generated.DependencyInjection.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
