using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;

namespace LightMapper.SourceGenerators;

internal sealed class MappingCodeEmitter
{
    private static readonly SymbolDisplayFormat FullyQualified =
        SymbolDisplayFormat.FullyQualifiedFormat;

    private readonly Compilation _compilation;
    private readonly ImmutableArray<MappingDeclaration> _pairs;
    private readonly SourceProductionContext _context;
    private readonly ImmutableHashSet<string> _pairKeys;

    public MappingCodeEmitter(
        Compilation compilation,
        ImmutableArray<MappingDeclaration> pairs,
        SourceProductionContext context)
    {
        _compilation = compilation;
        _pairs = pairs;
        _context = context;
        var builder = ImmutableHashSet.CreateBuilder<string>();
        foreach (var p in pairs)
            builder.Add(PairKey(p.Source, p.Destination));
        _pairKeys = builder.ToImmutable();
    }

    public void Emit()
    {
        var sb = new StringBuilder(16_384);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace LightMapper.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Compile-time generated object maps for this assembly.</summary>");
        sb.AppendLine("    internal static partial class LightMapDispatch");
        sb.AppendLine("    {");

        EmitGenericDispatch(sb);
        sb.AppendLine();

        foreach (var pair in _pairs)
        {
            EmitPairCoreMethod(sb, pair);
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine();
        EmitMapperRegistry(sb);
        sb.AppendLine("}");
        _context.AddSource("LightMapper.Generated.Map.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private void EmitGenericDispatch(StringBuilder sb)
    {
        sb.AppendLine("        /// <summary>Maps <typeparamref name=\"TSource\"/> to <typeparamref name=\"TDestination\"/> using generated logic (no reflection).</summary>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        internal static TDestination Map<TSource, TDestination>(TSource? source)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (source is null)");
        sb.AppendLine("                return default!;");
        sb.AppendLine();

        foreach (var pair in _pairs)
        {
            var srcFq = pair.Source.ToDisplayString(FullyQualified);
            var dstFq = pair.Destination.ToDisplayString(FullyQualified);
            var method = MethodName(pair.Source, pair.Destination);
            sb.AppendLine($"            if (typeof(TSource) == typeof({srcFq}) && typeof(TDestination) == typeof({dstFq}))");
            sb.AppendLine($"                return (TDestination)(object){method}(({srcFq})(object)source!)!;");
            sb.AppendLine();
        }

        sb.AppendLine("            throw new global::LightMapper.LightMapperException(typeof(TSource), typeof(TDestination));");
        sb.AppendLine("        }");
    }

    private void EmitMapperRegistry(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>Resolves <see cref=\"global::LightMapper.ILightMapper{TSource, TDestination}\"/> without reflection.</summary>");
        sb.AppendLine("    internal static class MapperRegistry");
        sb.AppendLine("    {");
        sb.AppendLine("        internal static global::LightMapper.ILightMapper<TSource, TDestination> Get<TSource, TDestination>()");
        sb.AppendLine("        {");

        foreach (var pair in _pairs)
        {
            var srcFq = pair.Source.ToDisplayString(FullyQualified);
            var dstFq = pair.Destination.ToDisplayString(FullyQualified);
            var mapperType = MapperTypeName(pair.Source, pair.Destination);
            sb.AppendLine($"            if (typeof(TSource) == typeof({srcFq}) && typeof(TDestination) == typeof({dstFq}))");
            sb.AppendLine($"                return (global::LightMapper.ILightMapper<TSource, TDestination>)(object){mapperType}.Instance;");
            sb.AppendLine();
        }

        sb.AppendLine("            throw new global::LightMapper.LightMapperException(typeof(TSource), typeof(TDestination));");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        foreach (var pair in _pairs)
            EmitMapperImplementation(sb, pair);
    }

    private void EmitMapperImplementation(StringBuilder sb, MappingDeclaration pair)
    {
        var srcFq = pair.Source.ToDisplayString(FullyQualified);
        var dstFq = pair.Destination.ToDisplayString(FullyQualified);
        var mapperType = MapperTypeName(pair.Source, pair.Destination);
        var method = MethodName(pair.Source, pair.Destination);

        sb.AppendLine();
        sb.AppendLine($"    internal sealed class {mapperType} : global::LightMapper.ILightMapper<{srcFq}, {dstFq}>");
        sb.AppendLine("    {");
        sb.AppendLine($"        internal static readonly {mapperType} Instance = new();");
        sb.AppendLine();
        sb.AppendLine($"        public {dstFq} Map({srcFq} source) => global::LightMapper.Generated.LightMapDispatch.{method}(source);");
        sb.AppendLine("    }");
    }

    private void EmitPairCoreMethod(StringBuilder sb, MappingDeclaration pair)
    {
        var srcFq = pair.Source.ToDisplayString(FullyQualified);
        var dstFq = pair.Destination.ToDisplayString(FullyQualified);
        var method = MethodName(pair.Source, pair.Destination);

        sb.AppendLine($"        internal static {dstFq} {method}({srcFq} source)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var __target = new {dstFq}();");

        foreach (var destProp in GetPublicInstanceWritableProperties(pair.Destination))
        {
            if (HasLightMapIgnore(destProp))
                continue;

            var sourceMemberName = GetLightMapFrom(destProp) ?? destProp.Name;
            var sourceProp = FindPublicReadableProperty(pair.Source, sourceMemberName);
            if (sourceProp is null)
            {
                if (GetLightMapFrom(destProp) is not null)
                {
                    _context.ReportDiagnostic(Diagnostic.Create(
                        DiagnosticDescriptors.MissingSourceMember,
                        PrimaryLocation(destProp),
                        destProp.Name,
                        sourceMemberName));
                }

                continue;
            }

            if (HasLightMapIgnore(sourceProp))
                continue;

            var assignment = TryBuildAssignment(sourceProp, destProp, pair.Location);
            if (assignment is not null)
            {
                sb.AppendLine($"            __target.{EscapeIdentifier(destProp.Name)} = {assignment};");
                continue;
            }

            if (TryEmitCollectionMapping(sb, sourceProp, destProp))
                continue;

            _context.ReportDiagnostic(Diagnostic.Create(
                DiagnosticDescriptors.IncompatibleMember,
                PrimaryLocation(destProp),
                destProp.Name,
                sourceProp.Type.ToDisplayString(SymbolDisplayFormat.CSharpShortErrorMessageFormat),
                destProp.Type.ToDisplayString(SymbolDisplayFormat.CSharpShortErrorMessageFormat)));
        }

        sb.AppendLine("            return __target;");
        sb.AppendLine("        }");
    }

    private string? TryBuildAssignment(IPropertySymbol sourceProp, IPropertySymbol destProp, Location reportLocation)
    {
        var srcType = sourceProp.Type;
        var dstType = destProp.Type;
        var conversion = _compilation.ClassifyConversion(srcType, dstType);
        if (conversion.Exists && conversion.IsImplicit)
            return $"source.{EscapeIdentifier(sourceProp.Name)}";

        if (TryGetNamedTypes(srcType, dstType, out var srcNamed, out var dstNamed) &&
            _pairKeys.Contains(PairKey(srcNamed, dstNamed)))
        {
            var access = $"source.{EscapeIdentifier(sourceProp.Name)}";
            var core = MethodName(srcNamed, dstNamed);
            var call = $"{core}({access})";

            if (srcType is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T })
                return $"{access}.HasValue ? {core}({access}.GetValueOrDefault()) : default!";

            if (!srcNamed.IsValueType && srcType.NullableAnnotation == NullableAnnotation.Annotated)
                return $"{access} is null ? default! : {call}";

            return call;
        }

        var widen = _compilation.ClassifyConversion(StripNullable(srcType), StripNullable(dstType));
        if (widen.Exists && widen.IsImplicit)
            return $"source.{EscapeIdentifier(sourceProp.Name)}";

        return null;
    }

    private bool TryEmitCollectionMapping(StringBuilder sb, IPropertySymbol sourceProp, IPropertySymbol destProp)
    {
        if (!TryGetSequenceShape(sourceProp.Type, out var srcElem, out var srcShape))
            return false;
        if (!TryGetSequenceShape(destProp.Type, out var dstElem, out var dstShape))
            return false;

        if (!TryResolveElementMapping(srcElem, dstElem, out var useMapper, out var mapExpr))
            return false;

        var destPropName = EscapeIdentifier(destProp.Name);
        var sourceAccess = $"source.{EscapeIdentifier(sourceProp.Name)}";
        var dstElemFq = dstElem.ToDisplayString(FullyQualified);
        var tmp = "__lm_" + SanitizeIdentifier(destProp.Name);

        var countExpr = srcShape == CollectionShape.Array
            ? $"{sourceAccess}.Length"
            : $"{sourceAccess}.Count";

        string MapItemExpr(string item) =>
            useMapper ? $"{mapExpr!}({item})" : item;

        if (dstShape == CollectionShape.Array)
        {
            sb.AppendLine($"            if ({sourceAccess} is null)");
            sb.AppendLine($"                __target.{destPropName} = global::System.Array.Empty<{dstElemFq}>();");
            sb.AppendLine("            else");
            sb.AppendLine("            {");
            sb.AppendLine($"                var {tmp} = new {dstElemFq}[{countExpr}];");
            sb.AppendLine($"                for (var __lm_i = 0; __lm_i < {tmp}.Length; __lm_i++)");
            sb.AppendLine($"                    {tmp}[__lm_i] = {MapItemExpr($"{sourceAccess}[__lm_i]")};");
            sb.AppendLine($"                __target.{destPropName} = {tmp};");
            sb.AppendLine("            }");
            return true;
        }

        sb.AppendLine($"            if ({sourceAccess} is null)");
        sb.AppendLine($"                __target.{destPropName} = new global::System.Collections.Generic.List<{dstElemFq}>();");
        sb.AppendLine("            else");
        sb.AppendLine("            {");
        sb.AppendLine($"                var {tmp} = new global::System.Collections.Generic.List<{dstElemFq}>({countExpr});");
        sb.AppendLine($"                foreach (var __lm_item in {sourceAccess})");
        sb.AppendLine($"                    {tmp}.Add({MapItemExpr("__lm_item")});");
        sb.AppendLine($"                __target.{destPropName} = {tmp};");
        sb.AppendLine("            }");
        return true;
    }

    private bool TryResolveElementMapping(ITypeSymbol srcElem, ITypeSymbol dstElem, out bool useMapper, out string? mapExpr)
    {
        useMapper = false;
        mapExpr = null;
        var s = StripNullable(srcElem);
        var d = StripNullable(dstElem);
        if (SymbolEqualityComparer.Default.Equals(s, d))
            return true;

        if (s is INamedTypeSymbol sn && d is INamedTypeSymbol dn && _pairKeys.Contains(PairKey(sn, dn)))
        {
            useMapper = true;
            mapExpr = MethodName(sn, dn);
            return true;
        }

        return false;
    }

    private enum CollectionShape
    {
        Array,
        List,
        ReadOnlyList,
    }

    private static bool TryGetSequenceShape(ITypeSymbol type, out ITypeSymbol element, out CollectionShape shape)
    {
        element = null!;
        shape = default;
        var t = StripNullable(type);
        if (t is IArrayTypeSymbol arr)
        {
            element = arr.ElementType;
            shape = CollectionShape.Array;
            return true;
        }

        if (t is not INamedTypeSymbol named || !named.IsGenericType || named.TypeArguments.Length != 1)
            return false;

        if (IsConstructedFromList(named))
        {
            element = named.TypeArguments[0];
            shape = CollectionShape.List;
            return true;
        }

        if (IsConstructedFromIReadOnlyList(named))
        {
            element = named.TypeArguments[0];
            shape = CollectionShape.ReadOnlyList;
            return true;
        }

        return false;
    }

    private static bool IsSystemCollectionsGeneric(INamedTypeSymbol named) =>
        string.Equals(
            named.ConstructedFrom.ContainingNamespace?.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            "global::System.Collections.Generic",
            StringComparison.Ordinal);

    private static bool IsConstructedFromList(INamedTypeSymbol named) =>
        named.IsGenericType &&
        IsSystemCollectionsGeneric(named) &&
        string.Equals(named.ConstructedFrom.MetadataName, "List`1", StringComparison.Ordinal);

    private static bool IsConstructedFromIReadOnlyList(INamedTypeSymbol named) =>
        named.IsGenericType &&
        IsSystemCollectionsGeneric(named) &&
        string.Equals(named.ConstructedFrom.MetadataName, "IReadOnlyList`1", StringComparison.Ordinal);

    private static string SanitizeIdentifier(string name)
    {
        var sb = new StringBuilder(name.Length);
        foreach (var ch in name)
        {
            if (char.IsLetterOrDigit(ch))
                sb.Append(ch);
            else
                sb.Append('_');
        }

        return sb.Length == 0 ? "list" : sb.ToString();
    }

    private static bool TryGetNamedTypes(ITypeSymbol srcType, ITypeSymbol dstType, out INamedTypeSymbol srcNamed, out INamedTypeSymbol dstNamed)
    {
        srcNamed = null!;
        dstNamed = null!;
        var s = StripNullable(srcType);
        var d = StripNullable(dstType);
        if (s is not INamedTypeSymbol sn)
            return false;
        if (d is not INamedTypeSymbol dn)
            return false;
        srcNamed = sn;
        dstNamed = dn;
        return true;
    }

    private static ITypeSymbol StripNullable(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } named)
            return named.TypeArguments[0];
        return type;
    }

    private static IEnumerable<IPropertySymbol> GetPublicInstanceWritableProperties(INamedTypeSymbol type)
    {
        foreach (var member in type.GetMembers())
        {
            if (member is not IPropertySymbol prop)
                continue;
            if (prop.IsStatic || prop.IsIndexer)
                continue;
            if (prop.DeclaredAccessibility != Accessibility.Public)
                continue;
            if (prop.SetMethod is null)
                continue;
            yield return prop;
        }
    }

    private static IPropertySymbol? FindPublicReadableProperty(INamedTypeSymbol type, string name)
    {
        foreach (var member in type.GetMembers())
        {
            if (member is not IPropertySymbol prop)
                continue;
            if (prop.Name != name)
                continue;
            if (prop.IsStatic || prop.IsIndexer)
                continue;
            if (prop.DeclaredAccessibility != Accessibility.Public)
                continue;
            if (prop.GetMethod is null)
                continue;
            return prop;
        }

        return null;
    }

    private static bool HasLightMapIgnore(IPropertySymbol prop)
    {
        foreach (var attr in prop.GetAttributes())
        {
            if (attr.AttributeClass?.ToDisplayString() == "LightMapper.LightMapIgnoreAttribute")
                return true;
        }

        return false;
    }

    private static string? GetLightMapFrom(IPropertySymbol prop)
    {
        foreach (var attr in prop.GetAttributes())
        {
            if (attr.AttributeClass?.ToDisplayString() != "LightMapper.LightMapFromAttribute")
                continue;
            if (attr.ConstructorArguments.Length > 0 && attr.ConstructorArguments[0].Value is string s)
                return s;
        }

        return null;
    }

    internal static string MethodName(INamedTypeSymbol source, INamedTypeSymbol destination) =>
        "Map_" + Sanitize(source) + "_to_" + Sanitize(destination);

    internal static string MapperTypeName(INamedTypeSymbol source, INamedTypeSymbol destination) =>
        "LightMapper__" + Sanitize(source) + "__" + Sanitize(destination);

    private static string Sanitize(INamedTypeSymbol type)
    {
        var raw = type.ToDisplayString(FullyQualified);
        var sb = new StringBuilder(raw.Length);
        foreach (var ch in raw)
        {
            if (char.IsLetterOrDigit(ch))
                sb.Append(ch);
            else
                sb.Append('_');
        }

        return sb.ToString();
    }

    private static Location PrimaryLocation(ISymbol symbol) =>
        symbol.Locations.IsEmpty ? Location.None : symbol.Locations[0];

    private static string PairKey(INamedTypeSymbol source, INamedTypeSymbol destination) =>
        source.ToDisplayString(FullyQualified) + " -> " + destination.ToDisplayString(FullyQualified);

    private static string EscapeIdentifier(string name) =>
        SyntaxFacts.GetKeywordKind(name) != SyntaxKind.None || SyntaxFacts.GetContextualKeywordKind(name) != SyntaxKind.None
            ? "@" + name
            : name;
}
