using System;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace LightMapper.SourceGenerators;

internal sealed class MappingCodeEmitter
{
    private static readonly SymbolDisplayFormat FullyQualified =
        SymbolDisplayFormat.FullyQualifiedFormat;

    private readonly Compilation _compilation;
    private readonly ImmutableArray<MappingDeclaration> _pairs;
    private readonly SourceProductionContext _context;
    private readonly ImmutableHashSet<string> _pairKeys;
    private readonly MappingMemberEmitter _memberEmitter;

    public MappingCodeEmitter(
        Compilation compilation,
        ImmutableArray<MappingDeclaration> pairs,
        SourceProductionContext context)
    {
        _compilation = compilation;
        _pairs = pairs;
        _context = context;
        var builder = ImmutableHashSet.CreateBuilder<string>();
        foreach (var p in pairs)
            builder.Add(MappingSymbolExtensions.PairKey(p.Source, p.Destination));
        _pairKeys = builder.ToImmutable();
        _memberEmitter = new MappingMemberEmitter(compilation, _pairKeys, context);
    }

    public void Emit()
    {
        EmitDispatchFile();
        EmitPublicFacadeFile();
    }

    private void EmitDispatchFile()
    {
        var sb = new StringBuilder(16_384);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace LightMapper.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Compile-time generated object maps for this assembly.</summary>");
        sb.AppendLine("    internal static partial class LightMapDispatch");
        sb.AppendLine("    {");

        EmitGenericDispatch(sb, "Map", "Map", isMapTo: false);
        sb.AppendLine();
        EmitGenericDispatch(sb, "MapTo", "MapTo", isMapTo: true);
        sb.AppendLine();

        foreach (var pair in _pairs)
        {
            EmitPairMapMethod(sb, pair);
            sb.AppendLine();
            EmitPairMapToMethod(sb, pair);
            sb.AppendLine();
        }

        sb.AppendLine("    }");
        sb.AppendLine();
        EmitMapperRegistry(sb);
        sb.AppendLine("}");

        _context.AddSource("LightMapper.Generated.Map.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private void EmitPublicFacadeFile()
    {
        var sb = new StringBuilder(4_096);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace LightMapper.Generated");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Public mapping entry points for this assembly.</summary>");
        sb.AppendLine("    public static class Maps");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>Maps <typeparamref name=\"TSource\"/> to a new <typeparamref name=\"TDestination\"/> instance.</summary>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        public static TDestination Map<TSource, TDestination>(TSource? source)");
        sb.AppendLine("            => LightMapDispatch.Map<TSource, TDestination>(source);");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>Maps <typeparamref name=\"TSource\"/> into an existing <typeparamref name=\"TDestination\"/> instance.</summary>");
        sb.AppendLine("        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("        public static void MapTo<TSource, TDestination>(TSource? source, TDestination destination)");
        sb.AppendLine("            where TDestination : notnull");
        sb.AppendLine("            => LightMapDispatch.MapTo<TSource, TDestination>(source, destination);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        _context.AddSource("LightMapper.Generated.Maps.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private void EmitGenericDispatch(StringBuilder sb, string methodName, string pairPrefix, bool isMapTo)
    {
        sb.AppendLine($"        [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        if (isMapTo)
        {
            sb.AppendLine($"        internal static void {methodName}<TSource, TDestination>(TSource? source, TDestination destination)");
            sb.AppendLine("            where TDestination : notnull");
        }
        else
        {
            sb.AppendLine($"        internal static TDestination {methodName}<TSource, TDestination>(TSource? source)");
        }

        sb.AppendLine("        {");
        if (!isMapTo)
        {
            sb.AppendLine("            if (source is null)");
            sb.AppendLine("                return default!;");
            sb.AppendLine();
        }
        else
        {
            sb.AppendLine("            if (source is null)");
            sb.AppendLine("                return;");
            sb.AppendLine();
        }

        foreach (var pair in _pairs)
        {
            var srcFq = pair.Source.ToDisplayString(FullyQualified);
            var dstFq = pair.Destination.ToDisplayString(FullyQualified);
            var method = pairPrefix + "_" + Sanitize(pair.Source) + "_to_" + Sanitize(pair.Destination);
            sb.AppendLine($"            if (typeof(TSource) == typeof({srcFq}) && typeof(TDestination) == typeof({dstFq}))");
            if (isMapTo)
                sb.AppendLine($"            {{ {method}(({srcFq})(object)source!, ({dstFq})(object)destination!); return; }}");
            else
                sb.AppendLine($"                return (TDestination)(object){method}(({srcFq})(object)source!)!;");
            sb.AppendLine();
        }

        if (isMapTo)
            sb.AppendLine("            throw new global::LightMapper.LightMapperException(typeof(TSource), typeof(TDestination));");
        else
            sb.AppendLine("            throw new global::LightMapper.LightMapperException(typeof(TSource), typeof(TDestination));");

        sb.AppendLine("        }");
    }

    private void EmitMapperRegistry(StringBuilder sb)
    {
        sb.AppendLine("    /// <summary>Resolves <see cref=\"global::LightMapper.ILightMapper{TSource, TDestination}\"/> without reflection.</summary>");
        sb.AppendLine("    internal static class MapperRegistry");
        sb.AppendLine("    {");
        sb.AppendLine("        internal static global::LightMapper.ILightMapper<TSource, TDestination> Get<TSource, TDestination>()");
        sb.AppendLine("            where TDestination : notnull");
        sb.AppendLine("        {");

        foreach (var pair in _pairs)
        {
            var srcFq = pair.Source.ToDisplayString(FullyQualified);
            var dstFq = pair.Destination.ToDisplayString(FullyQualified);
            var mapperType = MapperTypeName(pair.Source, pair.Destination);
            sb.AppendLine($"            if (typeof(TSource) == typeof({srcFq}) && typeof(TDestination) == typeof({dstFq}))");
            sb.AppendLine($"                return (global::LightMapper.ILightMapper<TSource, TDestination>)(object){mapperType}.Instance;");
            sb.AppendLine();
        }

        sb.AppendLine("            throw new global::LightMapper.LightMapperException(typeof(TSource), typeof(TDestination));");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        foreach (var pair in _pairs)
            EmitMapperImplementation(sb, pair);
    }

    private void EmitMapperImplementation(StringBuilder sb, MappingDeclaration pair)
    {
        var srcFq = pair.Source.ToDisplayString(FullyQualified);
        var dstFq = pair.Destination.ToDisplayString(FullyQualified);
        var mapperType = MapperTypeName(pair.Source, pair.Destination);
        var mapMethod = MethodName(pair.Source, pair.Destination);
        var mapToMethod = MapToMethodName(pair.Source, pair.Destination);

        sb.AppendLine();
        sb.AppendLine($"    internal sealed class {mapperType} : global::LightMapper.ILightMapper<{srcFq}, {dstFq}>");
        sb.AppendLine("    {");
        sb.AppendLine($"        internal static readonly {mapperType} Instance = new();");
        sb.AppendLine();
        sb.AppendLine($"        public {dstFq} Map({srcFq} source) => global::LightMapper.Generated.LightMapDispatch.{mapMethod}(source);");
        sb.AppendLine($"        public void MapTo({srcFq} source, {dstFq} destination) => global::LightMapper.Generated.LightMapDispatch.{mapToMethod}(source, destination);");
        sb.AppendLine("    }");
    }

    private void EmitPairMapMethod(StringBuilder sb, MappingDeclaration pair)
    {
        var srcFq = pair.Source.ToDisplayString(FullyQualified);
        var dstFq = pair.Destination.ToDisplayString(FullyQualified);
        var method = MethodName(pair.Source, pair.Destination);

        sb.AppendLine($"        internal static {dstFq} {method}({srcFq} source)");
        sb.AppendLine("        {");
        sb.AppendLine($"            var __target = new {dstFq}();");
        _memberEmitter.EmitMembers(sb, pair, "source", "__target");
        if (SourceImplementsAfterMap(pair.Source, pair.Destination))
            EmitAfterMapHook(sb, pair);
        sb.AppendLine("            return __target;");
        sb.AppendLine("        }");
    }

    private void EmitPairMapToMethod(StringBuilder sb, MappingDeclaration pair)
    {
        var srcFq = pair.Source.ToDisplayString(FullyQualified);
        var dstFq = pair.Destination.ToDisplayString(FullyQualified);
        var method = MapToMethodName(pair.Source, pair.Destination);

        sb.AppendLine($"        internal static void {method}({srcFq} source, {dstFq} destination)");
        sb.AppendLine("        {");
        _memberEmitter.EmitMembers(sb, pair, "source", "destination");
        if (SourceImplementsAfterMap(pair.Source, pair.Destination))
            EmitAfterMapHook(sb, pair, destinationVariable: "destination");
        sb.AppendLine("        }");
    }

    private static void EmitAfterMapHook(StringBuilder sb, MappingDeclaration pair, string destinationVariable = "__target")
    {
        var dstFq = pair.Destination.ToDisplayString(FullyQualified);
        sb.AppendLine($"            ((global::LightMapper.ILightMapperAfterMap<{dstFq}>)source).AfterMap({destinationVariable});");
    }

    private bool SourceImplementsAfterMap(INamedTypeSymbol source, INamedTypeSymbol destination)
    {
        var hook = _compilation.GetTypeByMetadataName("LightMapper.ILightMapperAfterMap`1");
        if (hook is null)
            return false;

        var constructed = hook.Construct(destination);
        foreach (var iface in source.AllInterfaces)
        {
            if (SymbolEqualityComparer.Default.Equals(iface, constructed))
                return true;
        }

        return false;
    }

    internal static string MethodName(INamedTypeSymbol source, INamedTypeSymbol destination) =>
        "Map_" + Sanitize(source) + "_to_" + Sanitize(destination);

    internal static string MapToMethodName(INamedTypeSymbol source, INamedTypeSymbol destination) =>
        "MapTo_" + Sanitize(source) + "_to_" + Sanitize(destination);

    internal static string MapperTypeName(INamedTypeSymbol source, INamedTypeSymbol destination) =>
        "LightMapper__" + Sanitize(source) + "__" + Sanitize(destination);

    private static string Sanitize(INamedTypeSymbol type)
    {
        var raw = type.ToDisplayString(FullyQualified);
        var sb = new StringBuilder(raw.Length);
        foreach (var ch in raw)
        {
            if (char.IsLetterOrDigit(ch))
                sb.Append(ch);
            else
                sb.Append('_');
        }

        return sb.ToString();
    }
}
